data1 = [
    {
        'id': 71054, 
        'name': '白80-1', 
        'location': {
            'y': -1, 
            'rotate_y': 0,
             'rotate_x': 0, 
             'x': -1, 
             'z': 0, 
             'rotate_z': 0
            }, 
            'zoom': {
                'x': 0.2, 
                'y': 0.2, 
                'z': 0.2
            }, 
            'configuration': None, 
            'created_at': '2025-11-26T16:01:26.698+08:00', 
            'updated_at': '2025-11-27T00:15:07.148+08:00', 
            'light_id': None, 
            'ar_object_owner_id': None, 
            'ar_object_owner_type': None, 
            'model': {
                'type': 8, 
                'fields': {
                    'visible_distance': 20, 
                    'is_metal': False, 'is_hidden': False, 'is_allow_pinch': False, 'width': 1, 'height': 1, 'face_me': False, 'is_ignore': False, 'is_double_sided': False, 'animation_speed': None, 'start_frame': None, 'end_frame': None, 'fps': None, 'multiply_number': None, 'multiply_radius': None, 'multiply_range': None, 'multiply_is_zero_y': False, 'is_occlusion': False, 'prefixes': ['api/v1/ar_objects', 'api/ar_objects', 'api/base', 'application'], 'template': 'ar_objects_from_scene', 'layout': {}}, 'texture': None, 'ios_texture': {'id': '28894', 'url': 'https://assets.lig.com.tw/ar_asset/dtw2jp6asla7owbhzjjgs4zsawas.glb'}, 'android_texture': {'id': '28894', 'url': 'https://assets.lig.com.tw/ar_asset/dtw2jp6asla7owbhzjjgs4zsawas.glb'}}, 'actions': None, 'transparency': 1.0, 'group': 1, 'zone_id': None, 'events': [{'id': 1, 'values': {}, 'actions': [{'id': 24, 'values': {'group': 1, 'delay_time': 0, 'impact_feedback_style': 0}}, {'id': 19, 'values': {'group': 1, 'transparency': 1, 'obj_id': 71049, 'delay_time': 0, 'time': 0.10000000149011612}}, {'id': 19, 'values': {'group': 2, 'transparency': 0, 'delay_time': 0, 'time': 0.5}}]}], 'scene_id': 4113, 'sub_events': None, 'is_child': False},
{'id': 71057, 'name': '闖關-1-2', 'location': {'y': -1, 'rotate_y': 0, 'rotate_x': 0, 'x': -1, 'z': 0, 'rotate_z': 0}, 'zoom': {'x': 0.4797, 'y': 0.4797, 'z': 0.4797}, 'configuration': None, 'created_at': '2025-11-26T23:16:40.042+08:00', 'updated_at': '2025-11-27T00:16:49.114+08:00', 'light_id': None, 'ar_object_owner_id': None, 'ar_object_owner_type': None, 'model': {'type': 5, 'fields': {'width': 1, 'height': 1, 'face_me': True, 'is_ignore': False, 'visible_distance': 20, 'is_hidden': False, 'is_size_scale_lock': True, 'is_allow_pinch': False, 'is_double_sided': False, 'is_occlusion': False, 'bloom_intensity': 0, 'bloom_radius': 0, 'prefixes': ['api/v1/ar_objects', 'api/ar_objects', 'api/base', 'application'], 'template': 'ar_objects_from_scene', 'layout': {}}, 'texture': {'url': 'https://assets.lig.com.tw/ar_asset/d5td8ic1n12vtayf6jfbja83j3ri.png', 'id': '28889'}, 'ios_texture': {'content_type': 'image/png'}, 'android_texture': {'content_type': 'image/png'}}, 'actions': None, 'transparency': 1.0, 'group': 1, 'zone_id': None, 'events': [], 'scene_id': 4113, 'sub_events': None, 'is_child': False},
{'id': 71053, 'name': '闖關-3-2', 'location': {'y': -0.7, 'rotate_y': 0.0, 'z': 0.5, 'x': 3.0, 'rotate_x': 0.0, 'rotate_z': 0.0}, 'zoom': {'x': 1.0, 'y': 1.0, 'z': 1.0}, 'configuration': None, 'created_at': '2025-11-26T15:58:42.972+08:00', 'updated_at': '2025-11-26T23:48:37.640+08:00', 'light_id': None, 'ar_object_owner_id': None, 'ar_object_owner_type': None, 'model': {'type': 5, 'fields': {'width': 1.0, 'height': 1.0, 'face_me': False, 'is_ignore': True, 'visible_distance': 20.0, 'is_hidden': False, 'is_size_scale_lock': True, 'is_allow_pinch': False, 'is_double_sided': True, 'is_occlusion': False, 'bloom_intensity': 0.0, 'bloom_radius': 0.0, 'prefixes': ['api/v1/ar_objects', 'api/ar_objects', 'api/base', 'application'], 'template': 'ar_objects_from_scene', 'layout': {}}, 'texture': {'url': 'https://assets.lig.com.tw/ar_asset/5u1iluya4cbobgflxi4nypuejgzs.png', 'id': '28893', 'content_type': 'image/png'}, 'ios_texture': {'content_type': 'image/png'}, 'android_texture': {'content_type': 'image/png'}}, 'actions': None, 'transparency': 0.0, 'group': 1, 'zone_id': None, 'events': [], 'scene_id': 4113, 'sub_events': None, 'is_child': False},
{'id': 71051, 'name': '闖關-2-2', 'location': {'y': -0.7, 'rotate_y': 0.0, 'z': 0.5, 'x': 2.0, 'rotate_x': 0.0, 'rotate_z': 0.0}, 'zoom': {'x': 1.0, 'y': 1.0, 'z': 1.0}, 'configuration': None, 'created_at': '2025-11-26T15:58:35.187+08:00', 'updated_at': '2025-11-27T00:14:30.678+08:00', 'light_id': None, 'ar_object_owner_id': None, 'ar_object_owner_type': None, 'model': {'type': 5, 'fields': {'width': 1.0, 'height': 1.0, 'face_me': False, 'is_ignore': True, 'visible_distance': 20.0, 'is_hidden': False, 'is_size_scale_lock': True, 'is_allow_pinch': False, 'is_double_sided': True, 'is_occlusion': False, 'bloom_intensity': 0.0, 'bloom_radius': 0.0, 'prefixes': ['api/v1/ar_objects', 'api/ar_objects', 'api/base', 'application'], 'template': 'ar_objects_from_scene', 'layout': {}}, 'texture': {'url': 'https://assets.lig.com.tw/ar_asset/86uxwsi3z5typ6ou2c5avhixxcsb.png', 'id': '28891', 'content_type': 'image/png'}, 'ios_texture': {'content_type': 'image/png'}, 'android_texture': {'content_type': 'image/png'}}, 'actions': None, 'transparency': 0.0, 'group': 1, 'zone_id': None, 'events': [], 'scene_id': 4113, 'sub_events': None, 'is_child': False},
{'id': 71052, 'name': 'ans-3_png', 'location': {'y': -1.0, 'rotate_y': 0.0, 'z': 0.5, 'x': 3.0, 'rotate_x': 0.0, 'rotate_z': 0.0}, 'zoom': {'x': 1.0, 'y': 1.0, 'z': 1.0}, 'configuration': None, 'created_at': '2025-11-26T15:58:38.433+08:00', 'updated_at': '2025-11-26T23:48:37.484+08:00', 'light_id': None, 'ar_object_owner_id': None, 'ar_object_owner_type': None, 'model': {'type': 5, 'fields': {'width': 1.0, 'height': 1.0, 'face_me': False, 'is_ignore': True, 'visible_distance': 20.0, 'is_hidden': False, 'is_size_scale_lock': True, 'is_allow_pinch': False, 'is_double_sided': True, 'is_occlusion': False, 'bloom_intensity': 0.0, 'bloom_radius': 0.0, 'prefixes': ['api/v1/ar_objects', 'api/ar_objects', 'api/base', 'application'], 'template': 'ar_objects_from_scene', 'layout': {}}, 'texture': {'url': 'https://assets.lig.com.tw/ar_asset/yq354js0vuc382wpq2kg7gldfpfs.png', 'id': '28898', 'content_type': 'image/png'}, 'ios_texture': {'content_type': 'image/png'}, 'android_texture': {'content_type': 'image/png'}}, 'actions': None, 'transparency': 1.0, 'group': 1, 'zone_id': None, 'events': [], 'scene_id': 4113, 'sub_events': None, 'is_child': False},
{'id': 71050, 'name': 'ans-2_png', 'location': {'y': -1.0, 'rotate_y': 0.0, 'z': 0.5, 'x': 2.0, 'rotate_x': 0.0, 'rotate_z': 0.0}, 'zoom': {'x': 1.0, 'y': 1.0, 'z': 1.0}, 'configuration': None, 'created_at': '2025-11-26T15:58:31.588+08:00', 'updated_at': '2025-11-26T23:48:37.434+08:00', 'light_id': None, 'ar_object_owner_id': None, 'ar_object_owner_type': None, 'model': {'type': 5, 'fields': {'width': 1.0, 'height': 1.0, 'face_me': False, 'is_ignore': True, 'visible_distance': 20.0, 'is_hidden': False, 'is_size_scale_lock': True, 'is_allow_pinch': False, 'is_double_sided': True, 'is_occlusion': False, 'bloom_intensity': 0.0, 'bloom_radius': 0.0, 'prefixes': ['api/v1/ar_objects', 'api/ar_objects', 'api/base', 'application'], 'template': 'ar_objects_from_scene', 'layout': {}}, 'texture': {'url': 'https://assets.lig.com.tw/ar_asset/7cmphjrb3atk9e8ajp711cjhkdb2.png', 'id': '28899', 'content_type': 'image/png'}, 'ios_texture': {'content_type': 'image/png'}, 'android_texture': {'content_type': 'image/png'}}, 'actions': None, 'transparency': 1.0, 'group': 1, 'zone_id': None, 'events': [], 'scene_id': 4113, 'sub_events': None, 'is_child': False},
{'id': 71048, 'name': 'ans-1_png', 'location': {'y': -1.0, 'rotate_y': 0.0, 'z': 0.5, 'x': 1.0, 'rotate_x': 0.0, 'rotate_z': 0.0}, 'zoom': {'x': 1.0, 'y': 1.0, 'z': 1.0}, 'configuration': None, 'created_at': '2025-11-26T15:58:24.845+08:00', 'updated_at': '2025-11-26T23:48:37.834+08:00', 'light_id': None, 'ar_object_owner_id': None, 'ar_object_owner_type': None, 'model': {'type': 5, 'fields': {'width': 1.0, 'height': 1.0, 'face_me': False, 'is_ignore': True, 'visible_distance': 20.0, 'is_hidden': False, 'is_size_scale_lock': True, 'is_allow_pinch': False, 'is_double_sided': True, 'is_occlusion': False, 'bloom_intensity': 0.0, 'bloom_radius': 0.0, 'prefixes': ['api/v1/ar_objects', 'api/ar_objects', 'api/base', 'application'], 'template': 'ar_objects_from_scene', 'layout': {}}, 'texture': {'url': 'https://assets.lig.com.tw/ar_asset/0wxdhpeun3ilnnji9n3kk09p1joj.png', 'id': '28897', 'content_type': 'image/png'}, 'ios_texture': {'content_type': 'image/png'}, 'android_texture': {'content_type': 'image/png'}}, 'actions': None, 'transparency': 1.0, 'group': 1, 'zone_id': None, 'events': [], 'scene_id': 4113, 'sub_events': None, 'is_child': False},
{'id': 71049, 'name': '闖關-1-2', 'location': {'y': -0.7, 'rotate_y': 0.0, 'z': 0.5, 'x': 1.0, 'rotate_x': 0.0, 'rotate_z': 0.0}, 'zoom': {'x': 1.0, 'y': 1.0, 'z': 1.0}, 'configuration': None, 'created_at': '2025-11-26T15:58:27.879+08:00', 'updated_at': '2025-11-26T23:48:37.383+08:00', 'light_id': None, 'ar_object_owner_id': None, 'ar_object_owner_type': None, 'model': {'type': 5, 'fields': {'width': 1.0, 'height': 1.0, 'face_me': False, 'is_ignore': True, 'visible_distance': 20.0, 'is_hidden': False, 'is_size_scale_lock': True, 'is_allow_pinch': False, 'is_double_sided': True, 'is_occlusion': False, 'bloom_intensity': 0.0, 'bloom_radius': 0.0, 'prefixes': ['api/v1/ar_objects', 'api/ar_objects', 'api/base', 'application'], 'template': 'ar_objects_from_scene', 'layout': {}}, 'texture': {'url': 'https://assets.lig.com.tw/ar_asset/d5td8ic1n12vtayf6jfbja83j3ri.png', 'id': '28889', 'content_type': 'image/png'}, 'ios_texture': {'content_type': 'image/png'}, 'android_texture': {'content_type': 'image/png'}}, 'actions': None, 'transparency': 0.0, 'group': 1, 'zone_id': None, 'events': [], 'scene_id': 4113, 'sub_events': None, 'is_child': False},
{'id': 71044, 'name': '介紹_凱歐斯、', 'location': {'y': -0.4, 'rotate_y': -180.0, 'z': -1.0, 'x': 1.48012, 'rotate_x': 0.0, 'rotate_z': 0.0}, 'zoom': {'x': 1.8, 'y': 1.8, 'z': 1.8}, 'configuration': None, 'created_at': '2025-11-26T15:26:50.944+08:00', 'updated_at': '2025-11-26T22:35:57.620+08:00', 'light_id': None, 'ar_object_owner_id': None, 'ar_object_owner_type': None, 'model': {'type': 5, 'fields': {'width': 1.0, 'height': 1.0, 'face_me': False, 'is_ignore': False, 'visible_distance': 5.0, 'is_hidden': False, 'is_size_scale_lock': True, 'is_allow_pinch': False, 'is_double_sided': True, 'is_occlusion': False, 'bloom_intensity': 0.0, 'bloom_radius': 0.0, 'prefixes': ['api/v1/ar_objects', 'api/ar_objects', 'api/base', 'application'], 'template': 'ar_objects_from_scene', 'layout': {}}, 'texture': {'url': 'https://assets.lig.com.tw/ar_asset/mo77rqwisni7jet0pty8cwn38sie.png', 'id': '28874', 'content_type': 'image/png'}, 'ios_texture': {'content_type': 'image/png'}, 'android_texture': {'content_type': 'image/png'}}, 'actions': None, 'transparency': 0.0, 'group': 1, 'zone_id': None, 'events': [], 'scene_id': 4113, 'sub_events': None, 'is_child': False},
{'id': 71045, 'name': 'Logo_勤崴國際LOGO', 'location': {'y': -1.5, 'rotate_y': 30.1902, 'z': 2.0, 'x': -18.0, 'rotate_x': 0.0, 'rotate_z': 0.0}, 'zoom': {'x': 1.0, 'y': 1.0, 'z': 1.0}, 'configuration': None, 'created_at': '2025-11-26T15:26:58.405+08:00', 'updated_at': '2025-11-26T22:33:07.975+08:00', 'light_id': None, 'ar_object_owner_id': None, 'ar_object_owner_type': None, 'model': {'type': 5, 'fields': {'width': 1.0, 'height': 1.0, 'face_me': False, 'is_ignore': False, 'visible_distance': 5.0, 'is_hidden': False, 'is_size_scale_lock': True, 'is_allow_pinch': False, 'is_double_sided': True, 'is_occlusion': False, 'bloom_intensity': 0.0, 'bloom_radius': 0.0, 'prefixes': ['api/v1/ar_objects', 'api/ar_objects', 'api/base', 'application'], 'template': 'ar_objects_from_scene', 'layout': {}}, 'texture': {'url': 'https://assets.lig.com.tw/ar_asset/0v8u7of6g4dlvme8nawq76yywt77.png', 'id': '28858', 'content_type': 'image/png'}, 'ios_texture': {'content_type': 'image/png'}, 'android_texture': {'content_type': 'image/png'}}, 'actions': None, 'transparency': 1.0, 'group': 1, 'zone_id': None, 'events': [{'id': 1, 'values': {}, 'actions': [{'id': 19, 'values': {'group': 1, 'transparency': 1.0, 'obj_id': 71046, 'delay_time': 0.0, 'play_count': 1, 'time': 0.5}}]}], 'scene_id': 4113, 'sub_events': None, 'is_child': False},
{'id': 71046, 'name': '介紹_秦威', 'location': {'y': -1.5, 'rotate_y': 30.1902, 'z': 2.50287, 'x': -18.86436, 'rotate_x': 0.0, 'rotate_z': 0.0}, 'zoom': {'x': 1.0, 'y': 1.0, 'z': 1.0}, 'configuration': None, 'created_at': '2025-11-26T15:27:09.004+08:00', 'updated_at': '2025-11-26T22:35:57.104+08:00', 'light_id': None, 'ar_object_owner_id': None, 'ar_object_owner_type': None, 'model': {'type': 5, 'fields': {'width': 1.0, 'height': 1.0, 'face_me': False, 'is_ignore': False, 'visible_distance': 5.0, 'is_hidden': False, 'is_size_scale_lock': True, 'is_allow_pinch': False, 'is_double_sided': True, 'is_occlusion': False, 'bloom_intensity': 0.0, 'bloom_radius': 0.0, 'prefixes': ['api/v1/ar_objects', 'api/ar_objects', 'api/base', 'application'], 'template': 'ar_objects_from_scene', 'layout': {}}, 'texture': {'url': 'https://assets.lig.com.tw/ar_asset/s6c1aq8rcr92ldmu1uvtyiaxfi3j.png', 'id': '28873', 'content_type': 'image/png'}, 'ios_texture': {'content_type': 'image/png'}, 'android_texture': {'content_type': 'image/png'}}, 'actions': None, 'transparency': 0.0, 'group': 1, 'zone_id': None, 'events': [], 'scene_id': 4113, 'sub_events': None, 'is_child': False},
{'id': 71041, 'name': 'Logo_LIG', 'location': {'y': -0.4, 'rotate_y': -55.4247, 'z': 3.86236, 'x': 2.60642, 'rotate_x': 0.0, 'rotate_z': 0.0}, 'zoom': {'x': 1.0, 'y': 1.0, 'z': 1.0}, 'configuration': None, 'created_at': '2025-11-26T15:24:13.254+08:00', 'updated_at': '2025-11-26T22:33:08.030+08:00', 'light_id': None, 'ar_object_owner_id': None, 'ar_object_owner_type': None, 'model': {'type': 5, 'fields': {'width': 1.0, 'height': 1.0, 'face_me': False, 'is_ignore': False, 'visible_distance': 5.0, 'is_hidden': False, 'is_size_scale_lock': True, 'is_allow_pinch': False, 'is_double_sided': True, 'is_occlusion': False, 'bloom_intensity': 0.0, 'bloom_radius': 0.0, 'prefixes': ['api/v1/ar_objects', 'api/ar_objects', 'api/base', 'application'], 'template': 'ar_objects_from_scene', 'layout': {}}, 'texture': {'url': 'https://assets.lig.com.tw/ar_asset/vuf1tyxv7t93pfs4yy43l93kq7b1.png', 'id': '28864', 'content_type': 'image/png'}, 'ios_texture': {'content_type': 'image/png'}, 'android_texture': {'content_type': 'image/png'}}, 'actions': None, 'transparency': 1.0, 'group': 1, 'zone_id': None, 'events': [{'id': 1, 'values': {}, 'actions': [{'id': 19, 'values': {'group': 1, 'transparency': 1.0, 'obj_id': 71042, 'delay_time': 0.0, 'play_count': 1, 'time': 0.5}}]}], 'scene_id': 4113, 'sub_events': None, 'is_child': False},
{'id': 71042, 'name': '介紹_LIG', 'location': {'y': -0.4, 'rotate_y': -59.6276, 'z': 2.63374, 'x': 1.57833, 'rotate_x': 0.0, 'rotate_z': 0.0}, 'zoom': {'x': 1.8901, 'y': 1.8901, 'z': 1.8901}, 'configuration': None, 'created_at': '2025-11-26T15:24:32.880+08:00', 'updated_at': '2025-11-26T22:35:57.453+08:00', 'light_id': None, 'ar_object_owner_id': None, 'ar_object_owner_type': None, 'model': {'type': 5, 'fields': {'width': 1.0, 'height': 1.0, 'face_me': False, 'is_ignore': False, 'visible_distance': 5.0, 'is_hidden': False, 'is_size_scale_lock': True, 'is_allow_pinch': False, 'is_double_sided': True, 'is_occlusion': False, 'bloom_intensity': 0.0, 'bloom_radius': 0.0, 'prefixes': ['api/v1/ar_objects', 'api/ar_objects', 'api/base', 'application'], 'template': 'ar_objects_from_scene', 'layout': {}}, 'texture': {'url': 'https://assets.lig.com.tw/ar_asset/jntpsglraszh5yppnyo6j8gmfaj7.png', 'id': '28884', 'content_type': 'image/png'}, 'ios_texture': {'content_type': 'image/png'}, 'android_texture': {'content_type': 'image/png'}}, 'actions': None, 'transparency': 0.0, 'group': 1, 'zone_id': None, 'events': [], 'scene_id': 4113, 'sub_events': None, 'is_child': False},
{'id': 71043, 'name': 'Logo_凱歐斯', 'location': {'y': -0.4, 'rotate_y': -180.0, 'z': -1.0, 'x': 3.0, 'rotate_x': 0.0, 'rotate_z': 0.0}, 'zoom': {'x': 1.0, 'y': 1.0, 'z': 1.0}, 'configuration': None, 'created_at': '2025-11-26T15:26:40.743+08:00', 'updated_at': '2025-11-26T22:33:07.739+08:00', 'light_id': None, 'ar_object_owner_id': None, 'ar_object_owner_type': None, 'model': {'type': 5, 'fields': {'width': 1.0, 'height': 1.0, 'face_me': False, 'is_ignore': False, 'visible_distance': 5.0, 'is_hidden': False, 'is_size_scale_lock': True, 'is_allow_pinch': False, 'is_double_sided': True, 'is_occlusion': False, 'bloom_intensity': 0.0, 'bloom_radius': 0.0, 'prefixes': ['api/v1/ar_objects', 'api/ar_objects', 'api/base', 'application'], 'template': 'ar_objects_from_scene', 'layout': {}}, 'texture': {'url': 'https://assets.lig.com.tw/ar_asset/8ldvl8vvkcrs0t1prxz0p1my2318.png', 'id': '28854', 'content_type': 'image/png'}, 'ios_texture': {'content_type': 'image/png'}, 'android_texture': {'content_type': 'image/png'}}, 'actions': None, 'transparency': 1.0, 'group': 1, 'zone_id': None, 'events': [{'id': 1, 'values': {}, 'actions': [{'id': 19, 'values': {'group': 1, 'transparency': 1.0, 'obj_id': 71044, 'delay_time': 0.0, 'play_count': 1, 'time': 0.5}}]}], 'scene_id': 4113, 'sub_events': None, 'is_child': False},
{'id': 71040, 'name': '介紹_神通', 'location': {'y': -0.4, 'rotate_y': -238.271, 'z': 9.36366, 'x': 0.58213, 'rotate_x': 0.0, 'rotate_z': 0.0}, 'zoom': {'x': 1.8, 'y': 1.8, 'z': 1.8}, 'configuration': None, 'created_at': '2025-11-26T15:23:40.931+08:00', 'updated_at': '2025-11-26T22:35:57.398+08:00', 'light_id': None, 'ar_object_owner_id': None, 'ar_object_owner_type': None, 'model': {'type': 5, 'fields': {'width': 1.0, 'height': 1.0, 'face_me': False, 'is_ignore': False, 'visible_distance': 5.0, 'is_hidden': False, 'is_size_scale_lock': True, 'is_allow_pinch': False, 'is_double_sided': True, 'is_occlusion': False, 'bloom_intensity': 0.0, 'bloom_radius': 0.0, 'prefixes': ['api/v1/ar_objects', 'api/ar_objects', 'api/base', 'application'], 'template': 'ar_objects_from_scene', 'layout': {}}, 'texture': {'url': 'https://assets.lig.com.tw/ar_asset/zaha4acfqalnvtio6d8o5uqokpoh.png', 'id': '28872', 'content_type': 'image/png'}, 'ios_texture': {'content_type': 'image/png'}, 'android_texture': {'content_type': 'image/png'}}, 'actions': None, 'transparency': 0.0, 'group': 1, 'zone_id': None, 'events': [], 'scene_id': 4113, 'sub_events': None, 'is_child': False},
{'id': 71038, 'name': '介紹_會家', 'location': {'y': -0.49409, 'rotate_y': -52.3628, 'z': 6.59231, 'x': 4.22632, 'rotate_x': 0.0, 'rotate_z': 0.0}, 'zoom': {'x': 1.5713, 'y': 1.5713, 'z': 1.5713}, 'configuration': None, 'created_at': '2025-11-26T15:23:18.602+08:00', 'updated_at': '2025-11-26T22:35:57.514+08:00', 'light_id': None, 'ar_object_owner_id': None, 'ar_object_owner_type': None, 'model': {'type': 5, 'fields': {'width': 1.0, 'height': 1.0, 'face_me': False, 'is_ignore': False, 'visible_distance': 5.0, 'is_hidden': False, 'is_size_scale_lock': True, 'is_allow_pinch': False, 'is_double_sided': True, 'is_occlusion': False, 'bloom_intensity': 0.0, 'bloom_radius': 0.0, 'prefixes': ['api/v1/ar_objects', 'api/ar_objects', 'api/base', 'application'], 'template': 'ar_objects_from_scene', 'layout': {}}, 'texture': {'url': 'https://assets.lig.com.tw/ar_asset/8z7b8fgwlsgnrqx7jieu8ioxv4u2.png', 'id': '28877', 'content_type': 'image/png'}, 'ios_texture': {'content_type': 'image/png'}, 'android_texture': {'content_type': 'image/png'}}, 'actions': None, 'transparency': 0.0, 'group': 1, 'zone_id': None, 'events': [], 'scene_id': 4113, 'sub_events': None, 'is_child': False},
]
